# import urllib library
from urllib.request import urlopen
import time
# import json
import json
# store the URL in url as 
# parameter for urlopen
urls = [
"https://api.polygon.io/v2/reference/financials/AMZN?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/SHOP?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/TTD?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/SQ?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/MELI?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/PYPL?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/TWLO?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/MDB?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/ANET?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/NFLX?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/AAPL?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/FB?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/PAYC?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/ETSY?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/MA?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/TDOC?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/OKTA?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/VEEV?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/APPN?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/DOCU?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/HUBS?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/AYX?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/TSLA?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/DIS?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/ROKU?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/CRM?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/GOOG?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/RDFN?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/NVDA?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/DDOG?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/ZS?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/PINS?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/CRWD?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/SBUX?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/ZM?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/AXON?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/ATVI?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/TEAM?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/ADBE?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/AMT?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/ISRG?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/TCEHY?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/TTWO?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/NET?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/WIX?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/SFIX?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/FSLY?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/ULTA?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/ALGN?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/CGNX?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/WDAY?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/JD?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/ILMN?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/FVRR?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/MNST?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/BL?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/ADSK?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/MKL?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/CMG?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/PTON?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/NOW?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/ZEN?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/IRBT?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/ACN?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/SWKS?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/MTCH?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/PRLB?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/UPST?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/SE?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/TWTR?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/EDIT?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/IQ?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/IPGP?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/BRK.B?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/UPWK?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/IDXX?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/Z?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/COST?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/GH?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/EA?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/SPLK?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/NVCR?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/MKC?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/EQIX?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/NTNX?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/MASI?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/TSCO?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/UI?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/ABNB?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/ZNGA?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/HQY?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/NVTA?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/ABMD?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/U?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/VRNS?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/FTNT?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/LULU?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/LYV?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/IBKR?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/AVAV?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/IIVI?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/LRCX?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/AX?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/NKE?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/NEE?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/MRNA?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/NEWR?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/BMBL?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/JKHY?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/DXCM?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/ASML?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/BZUN?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/SSNC?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/PLNT?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/BKNG?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/PANW?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/IONS?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/GILD?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/WING?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/TREX?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/LMND?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/CPNG?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/BIDU?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/INTU?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/BLUE?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/DASTY?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/XLNX?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/BYND?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/KMI?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/ROL?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/HCA?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/ICE?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/TXRH?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/FIVE?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/FDX?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/HAS?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/MTN?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/MIDD?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/BILI?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/LOGI?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/SNPS?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/FUBO?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/IT?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/CTAS?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/WAB?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/WSM?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/SKX?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/BCPC?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/FRPT?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/SAM?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/W?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/COUP?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/H?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/NTDOY?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/UBER?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/RBLX?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/OLLI?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/GDRX?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/CPRT?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/GDDY?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/LPSN?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/MOMO?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/NTES?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/RH?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/SIRI?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/SNBR?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/FDS?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/ALK?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/ZBRA?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/EBAY?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/ALKS?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/ALNY?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/AMGN?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/AVGO?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/BLKB?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/FSLR?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/GTLS?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/LKQ?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/MTZ?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/NICE?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/NUVA?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/NVO?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/RMD?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/SGEN?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/SWAV?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/VRTX?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/BIIB?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/EXEL?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/BB?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/SIVB?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/WAL?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/WM?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/BMRN?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/CASY?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/TWOU?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/BUD?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/UNH?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/CLB?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/TMUS?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/CRTO?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/UAA?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/CBOE?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/CME?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/LFUS?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/ODFL?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/PAC?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/RPM?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/MMM?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/CWH?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/CMI?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/EBS?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/WSO?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/OII?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/CVS?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/MAR?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/SHW?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/NYT?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/STAA?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/NXPI?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/TDG?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
"https://api.polygon.io/v2/reference/financials/TXT?limit=5&apiKey=8tMLADmu1Cnj84p0DmsyKcwiihl7s4nu",
]

  

fw = open("findata.txt", "a")
ctr = 0
# store the response of URL
for url in urls:	
	try:
		ctr = ctr + 1
		response = urlopen(url)
		# storing the JSON response 
		# from url in data
		data_json = json.loads(response.read())
	  
		# print the json response
		ticker = data_json['results'][0]['ticker']
		priceToEarningsRatio = data_json['results'][0]['priceToEarningsRatio']
		priceToBookValue =  data_json['results'][0]['priceToBookValue']
		debtToEquityRatio = data_json['results'][0]['debtToEquityRatio']
		freeCashFlow = data_json['results'][0]['freeCashFlow']
		fw.write('ticker = ' + str(ticker) + "\n")	
		fw.write('priceToEarningsRatio = ' + str(priceToEarningsRatio) + "\n")
		fw.write('priceToBookValue = ' + str(priceToBookValue) + "\n")
		fw.write('debtToEquityRatio = ' + str(debtToEquityRatio) + "\n")
		fw.write('freeCashFlow = ' + str(freeCashFlow) + "\n")
		fw.write("\n\n")
		if(ctr%5 == 0):
			time.sleep(61)

	except:
		continue	
		
fw.close()